services:
  main:
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        DEV_BUILD: "true"
    pull_policy: build
    image: transparencia-gov-br-main:latest
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - "docker/env/main"
      - "docker/env/main.local"
    volumes:
      - ${PWD}/docker/data/main:/data
      - ${PWD}:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-bookworm
    command: -c "config_file=/etc/postgresql/postgresql.conf"
    env_file:
      - "docker/env/db"
      - "docker/env/db.local"
    user: "${UID:-1000}:${GID:-1000}"
    shm_size: 8g
    volumes:
      - ${PWD}/docker/data/db:/var/lib/postgresql/data
      - ${PWD}/docker/conf/db/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5
